version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARG_BUNDLER_VERSION: 2.2.22
        ARG_RUBYGEMS_VERSION: 3.2.22
        ARG_COMPOSE_WAIT_VER: 2.9.0
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=web
      - TEST_APP_PORT=3001
    volumes:
      - bundle_cache:/bundle
      - .:/app
    stdin_open: true
    tty: true

  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    volumes:
      - /dev/shm:/dev/shm
    stdin_open: true
    tty: true

  # wait-middleware:
  #   build: .
  #   environment:
  #     WAIT_HOSTS: web:3001,selenium:4444
  #     WAIT_TIMEOUT: 40
  #     WAIT_HOST_CONNECT_TIMEOUT: 30
  #     WAIT_BEFORE: 0
  #     WAIT_AFTER: 0
  #     WAIT_SLEEP_INTERVAL: 1
  #   depends_on:
  #     - web
  #     - selenium
  #   command: /wait

volumes:
  bundle_cache:
