version: '3.1'

services:
  web:
    command: >
      bash -c "bin/rails server puma --binding 0.0.0.0 --port 3001 --environment test"
    ports:
      - 3001:3001

  selenium:
    ports:
      - 4444:4444
      - 5900:5900
      - 9517:9517
